Repository sider/devon_rex, pull requests merged in 2021-07, with the labels that each got.

#573 Configure Dependabot for Node.js Docker image
  .github/dependabot.yml
Labels: dependencies, dx

#578 Configure Dependabot for PHP Docker image
  .github/dependabot.yml
Labels: dependencies, dx

#582 Bump bundler from 2.2.21 to 2.2.22
  CHANGELOG.md
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby

#581 Bump aufgaben from 0.7.1 to 0.8.2
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby

#583 Preferred CMD form
  base/Dockerfile
  base/Dockerfile.erb
  swift/Dockerfile
  swift/Dockerfile.erb
Labels: refactoring

#584 Bump Ruby from 2.7.3 to 2.7.4
  .ruby-version
  CHANGELOG.md
  base/Dockerfile
  dotnet/Dockerfile
  go/Dockerfile
  java/Dockerfile
  npm/Dockerfile
  php/Dockerfile
  python/Dockerfile
  swift/Dockerfile
Labels: dependencies, ruby

#586 Bump bundler from 2.2.22 to 2.2.23
  CHANGELOG.md
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby

#590 Bump bundler from 2.2.23 to 2.2.24
  CHANGELOG.md
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby

#591 Narrow scope of `env.target_file`
  .github/workflows/bump-git.yml
Labels: refactoring

#592 Auto-bumping Bundler via Actions
  .github/workflows/bump-bundler.yml
Labels: dependencies, dx, ruby

#593 Bundle update
  Gemfile.lock
Labels: dependencies, ruby

#605 Fix the broken link on ChangeLog
  CHANGELOG.md
Labels: documentation

#606 Add docker/setup-buildx-action
  .github/workflows/build.yml
Labels: dx

#608 Refactor build action
  .github/workflows/build.yml
Labels: refactoring

#609 Bump aufgaben from 0.8.2 to 0.8.3
  Gemfile.lock
Labels: dependencies, ruby

#610 Fix publishing Docker images
  .github/workflows/build.yml
  CHANGELOG.md
Labels: bug

#611 Refactor build action
  .github/workflows/build.yml
  CHANGELOG.md
  Rakefile
Labels: refactoring
