Repository sider/devon_rex, pull requests merged in 2021-09, with the labels that each got.

#653 Bump bundler from 2.2.26 to 2.2.27
  CHANGELOG.md
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby

#652 Add Goodcheck rule for Java version
  goodcheck.yml
Labels: dx

#656 Fix build workflow by Dependabot
  .github/workflows/build.yml
Labels: dependencies, dx

#657 Add a Goodcheck rule for npm
  goodcheck.yml
Labels: dx
